FROM maven:3.8.6-openjdk-8 AS builder     

WORKDIR /app                                                       
COPY app-maven /app                                             

RUN mvn package                                            

FROM eclipse-temurin:8-jre-alpine                                  

COPY --from=builder /app/target/my-app-1.0-SNAPSHOT.jar /app.jar  

CMD ["java", "-jar", "/app.jar"]                                  